name = "solpa-gantt"
compatibility_date = "2026-06-30"
pages_build_output_dir = "public"

[vars]
NOTION_VERSION = "2022-06-28"

NOTION_READ_DATABASE_ID = "20175c38-e3be-4b38-b81e-e8394914431e"
NOTION_WRITE_DATABASE_ID = "b6e89562-3634-4ef2-bd75-c592a438e372"

NOTION_TITLE_PROP = "이름"
NOTION_DATE_PROP = "날짜"
NOTION_START_PROP = "날짜"
NOTION_CHANNEL_PROP = "채널명"
NOTION_PROJECT_PROP = "이름"
NOTION_DETAIL_PROP = "카테고리"
NOTION_CATEGORY_PROP = "카테고리"
NOTION_STATUS_PROP = "상태"
NOTION_ASSIGNEE_PROP = "사람"

NOTION_WRITE_TITLE_PROP = "프로젝트"
NOTION_WRITE_CHANNEL_PROP = "채널"
NOTION_WRITE_PROJECT_PROP = "프로젝트"
NOTION_WRITE_DETAIL_PROP = "일정"
NOTION_WRITE_DATE_PROP = "날짜"
NOTION_WRITE_STATUS_PROP = "상태"
NOTION_WRITE_ASSIGNEE_PROP = "담당자"
NOTION_WRITE_DESCRIPTION_PROP = "메모"

APP_ALLOW_TARGET_ARCHIVE = "false"
APP_EMBED_KEY = "140b034014a1a3d4141cfade6df012553e68"

[[kv_namespaces]]
binding = "SOLPA_GANTT_KV"
id = "44406088912b484986af75a31557eaf8"
